FORMAT: 1A
HOST: https://api-sms.pontaltech.com.br

# SMS

Api para envio de SMS

## Envio de SMS [/v1/messages]

### Novo Envio [POST]

Você pode enviar diferentes tipos de SMS nesta requisição

    + Headers
        Authorization: Basic {token}

+ Request (application/json)

        {
          "urlCallback":"http://abc.com/sdkfdsljfljfafjsd",
          "concat": true,
          "flashSms": true,
          "messages":[
            {
                "to": 11911111111,
                "message": "Mensagem",
                "variables": {
                "nome":"João",
                "data":"2020-10-21"
                }
            },{
                "to": 11911111112,
                "message": "Mensagem",
                "schedule": "2021-08-21T16:16:14Z",
                "account": 41
            },{
                "to": 11911111113,
                "message": "Mensagem",
                "schedule": "2021-08-17T23:16:14Z",
                "expireLimit": 30
            }
          ]
        }

+ Response 200 (application/json)

    + Body

            [
              {
                "to": 11911111111,
                "message": "Mensagem",
                "variables": {
                    "nome":"João",
                    "data":"2020-10-21"
                },
                "concat": false,
                "flash_sms": false,
                "client_id": 835,
                "expire_limit": null,
                "bill_factor": 1,
                "id": "64961860-feeb-11eb-9521-653ff1a944ef"
              },
              {
                "to": 11911111112,
                "message": "Mensagem",
                "schedule": "2021-08-21T16:16:14Z",
                "account": 41,
                "concat": false,
                "flash_sms": false,
                "client_id": 835,
                "variables": null,
                "expire_limit": null,
                "error": "Account invalida"
              },
              {
                "to": 11911111113,
                "message": "Mensagem",
                "expireLimit": 30,
                "concat": false,
                "flash_sms": false,
                "client_id": 835,
                "variables": null,
                "expire_limit": null,
                "bill_factor": 1,
                "id": "6496b4a0-feeb-11eb-9521-653ff1a944ef"
              }
            ]
            
+ Response 401 (application/json)

+ Request (application/json)

        {
          "urlCallback":"http://abc.com/sdkfdsljfljfafjsd",
          "concat": true,
          "flashSms": true,
          "messages":[
            {
                "message": "Mensagem",
                "variables": {
                "nome":"João",
                "data":"2020-10-21"
                }
            }
          ]
        }


+ Response 400 (application/json)

    + Body

            "Nenhuma mensagem válida"